LILI_FPMS/Controllers/ShiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LILI_FPMS;
using LILI_IMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LILI_IMS.Controllers
{
    [Authorize]
    public class ShiftController : Controller
    {
        private readonly dbFormulationProductionSystemContext _context;

        private readonly IHttpContextAccessor _httpContextAccessor;
        private static long GlobalPlantId;
        public ShiftController(dbFormulationProductionSystemContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            var plntid = _httpContextAccessor.HttpContext.Session.GetString("PlantId");
            if (!string.IsNullOrEmpty(plntid))
            {
                GlobalPlantId = long.Parse(plntid);
            }
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {

            

            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var shifts = from s in _context.TblShiftSetup
                            select s;
            shifts = shifts.Where(s => s.PlantId == GlobalPlantId);
            if (!String.IsNullOrEmpty(searchString))
            {
                shifts = shifts.Where(s => s.ShiftName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    shifts = shifts.OrderByDescending(s => s.ShiftName);
                    break;
                
                default:
                    shifts = shifts.OrderBy(s => s.ShiftName);
                    break;
            }
            int pageSize = 7;
            return View(await PaginatedList<TblShiftSetup>.CreateAsync(shifts.AsNoTracking(), pageNumber ?? 1, pageSize));

            //return View(await employees.AsNoTracking().ToListAsync());
        }

        public ActionResult Create()
        {
            TblShiftSetup entities = new TblShiftSetup();
            return View(entities);
            //return View();
        }

        [HttpPost, ActionName("CreateShift")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateShift(TblShiftSetup shift)
          {
            try
            {
                if (ModelState.IsValid)
                {
                    shift.Iuser = User.Identity.Name;
                    shift.Idate = DateTime.Now;
                    shift.PlantId = GlobalPlantId;
                    _context.Add(shift);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    ViewData["Error"] = "Error message text.";
                    return View(shift);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public bool Delete(int id)
        {
            try
            {
                TblShiftSetup shift = _context.TblShiftSetup.Where(s => s.Id == id).First();
                _context.TblShiftSetup.Remove(shift);
                _context.SaveChanges();
                return true;
                //return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return false;
                //return RedirectToAction(nameof(Index));
            }
        }

        public ActionResult Update(int id)
        {
            Models.TblShiftSetup shiftModel = new Models.TblShiftSetup();
            var dt = _context.TblShiftSetup.Where(s => s.Id == id).First();
            shiftModel.Id = dt.Id;
            shiftModel.ShiftCode = dt.ShiftCode;
            shiftModel.ShiftName = dt.ShiftName;
            shiftModel.StandardShiftHour = dt.StandardShiftHour;
            shiftModel.PlannedDownChangeTime = dt.PlannedDownChangeTime;
            shiftModel.ProductiveShiftHour = dt.ProductiveShiftHour;
            shiftModel.Comments = dt.Comments;
            shiftModel.ShiftStartTime= dt.ShiftStartTime;
            shiftModel.ShiftEndTime= dt.ShiftEndTime;
            return View(shiftModel);
        }

        [HttpPost, ActionName("UpdateShift")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateShift(int id, TblShiftSetup shift)
        {
            if (id != shift.Id)
            {
                return NotFound();
            }
            try
            {
                //eFTestContext.Update(shift);
                //await eFTestContext.SaveChangesAsync();

                var shiftToUpdate = await _context.TblShiftSetup.FirstOrDefaultAsync(s => s.Id == id);
                shiftToUpdate.Edate = DateTime.Now;
                shiftToUpdate.Euser = User.Identity.Name;
                if (await TryUpdateModelAsync<TblShiftSetup>(
                    shiftToUpdate,
                    "",
                    s => s.ShiftCode, s => s.ShiftName, s => s.StandardShiftHour, s => s.PlannedDownChangeTime, s => s.ProductiveShiftHour, s => s.Comments, s => s.Euser, s => s.Edate
                    , s => s.ShiftStartTime, s => s.ShiftEndTime))

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                //Log the error (uncomment ex variable name and write a log.)
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists, " +
                    "see your system administrator.");
            }
            return View(shift);
        }



    }
}

LILI_FPMS/Views/Shift/Create.cshtml
@model LILI_IMS.Models.TblShiftSetup

@*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>*@




@*<script src="~/lib/JQuery-unobtrusive-Ajax/jquery-ajax-unobtrusive-master/src/jquery.unobtrusive-ajax.js"></script>*@

<!-- Modal placeholder -->
<div id="modal-placeholder"></div>



<!-- Content Header (Page header) -->
<section class="content-header">
    @*<h1>
            Shift Setup
        </h1>*@
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Shift Setup</li>
        <li class="active">Add Shift</li>
    </ol>
</section>
<!-- Main content -->
<section class="content container-fluid">
    <!-- Horizontal Form -->
    <div class="box box-info" style="border:1px solid; border-color:cadetblue; padding:10px">
        @*<div class="box-header with-border">
                <h3 class="box-title">Add Shift</h3>
            </div>*@
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" asp-controller="Shift" method="post" asp-action="CreateShift">
            @*<div asp-validation-summary="ModelOnly" class="text-danger">
                    <span>Please correct the following errors</span>
                </div>*@



            @*@if (ViewData["Error"] != null)
                {
                    <div class="red">
                        <p><strong>Error:</strong> @ViewData["Error"].ToString()</p>
                    </div>
                }
                @if (TempData["Success"] != null)
                {
                    <div class="green">
                        <p><strong>Success:</strong> @TempData["Success"].ToString()</p>
                    </div>
                }*@





            <div class="box-body">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Shift Code</label>
                    <div class="col-sm-10">
                        <input type="text" asp-for="ShiftCode" class="form-control" placeholder="Shift Code">
                        <span asp-validation-for="ShiftCode"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Shift Name</label>
                    <div class="col-sm-10">
                        <input type="text" asp-for="ShiftName" class="form-control" placeholder="Shift Name">
                        <span asp-validation-for="ShiftName"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Standard Shift Hour</label>
                    <div class="col-sm-10">
                        <input type="text" asp-for="StandardShiftHour" class="form-control" placeholder="Standard Shift Hour" onkeypress='return isNumberKey(event)'>
                        <span asp-validation-for="StandardShiftHour"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Planned Down Change Time</label>
                    <div class="col-sm-10">
                        <input type="text" asp-for="PlannedDownChangeTime" class="form-control" placeholder="Planned Down Change Time" onkeypress='return isNumberKey(event)'>
                        <span asp-validation-for="PlannedDownChangeTime"></span>
                    </div>
                </div>


                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Productive Shift Hour</label>
                    <div class="col-sm-10">
                        <input type="text" asp-for="ProductiveShiftHour" class="form-control" placeholder="Productive Shift Hour" onkeypress='return isNumberKey(event)'>
                        <span asp-validation-for="ProductiveShiftHour"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Comments</label>
                    <div class="col-sm-10">
                        <input type="text" asp-for="Comments" class="form-control" placeholder="Comments">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Shift Start Time</label>
                    <div class="col-sm-2">
                        <input type="time" asp-for="ShiftStartTime" class="form-control" placeholder="ShiftStartTime">
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Shift End Time</label>
                    <div class="col-sm-2">
                        <input type="time" asp-for="ShiftEndTime" class="form-control" placeholder="ShiftEndTime">
                    </div>
                </div>

                
            </div>


            <!-- /.box-body -->
            <div class="box-footer">

                <a class="btn btn-mini btn-primary" href='@Url.Content("/Shift/Index")'>Cancel</a>
                <button type="submit" class="btn btn-info pull-right">Create</button>

            </div>
            <!-- /.box-footer -->
        </form>
    </div>
    <!-- /.box -->
</section>




<script type="text/javascript">

    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode
        if (charCode > 31 && (charCode != 46 && (charCode < 48 || charCode > 57)))
            return false;
        return true;
    }


</script>

LILI_FPMS/Views/Shift/Index.cshtml
@model PaginatedList<LILI_IMS.Models.TblShiftSetup>



<section class="content-header">
    @*<h1>
            Shift Setup
        </h1>*@
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Shift Setup</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="box-body">
            <div class="col-xs-12">
                <div class="col-sm-11">
                    <form asp-action="Index" method="get">
                        <div class="form-actions no-color">
                            <div class="col-sm-12">
                                <div class="col-sm-6">
                                    <input type="text" name="SearchString" value="@ViewData["currentFilter"]" class="form-control" placeholder="Search for...">
                                </div>
                                <div class="col-sm-3">
                                    <span class="input-group-btn">
                                        @*<input  value="Search" class="btn btn-default" style="background-color:#4d4a45; color:white;" />*@
                                        <button type="submit" class="btn btn-search" value="Search"><i class="fa fa-search fa-fw"></i>Search</button>
                                    </span>
                                </div>
                                <div class="col-sm-3">
                                    @*<a asp-action="Index">Back to Full List</a>*@
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
                <div class="col-sm-1">
                    <a class="btn btn-action" href="/Shift/Create">
                        <i class="fa fa-plus fa-fw"></i>Add
                    </a>
                </div>
            </div>
            @*<table id="example1" class="table table-bordered table-striped roundedCorners">*@
            <div class="grid-table-header">
                <table id="ShiftTable" class="table roundedCorners">
                    <thead>
                        <tr style="background-color:#6c7ae0; color:white; height:50px;">
                            <th style="text-align:center; width:7%">Id</th>
                            <th style="text-align:center;  width:10%">Shift Code</th>
                            <th style="text-align:center; width:10%">
                                <a style="color:white;" asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Shift Name <i class="fa fa-sort" style="font-size:20px;color:sandybrown;"></i></a>
                            </th>
                            <th style="text-align:center; width:10%">Standard Shift Hour</th>
                            <th style="text-align:center;  width:10%">Planned Down Change Time</th>
                            <th style="text-align:center;  width:10%">Productive Shift Hour</th>
                            <th style="text-align:center;  width:"30">Comments</th>
                            <th style="text-align:center; width:10%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Id)</td>
                            <td>@Html.DisplayFor(modelItem => item.ShiftCode)</td>
                            <td>@Html.DisplayFor(modelItem => item.ShiftName)</td>
                            <td>@Html.DisplayFor(modelItem => item.StandardShiftHour)</td>
                            <td>@Html.DisplayFor(modelItem => item.PlannedDownChangeTime)</td>
                            <td>@Html.DisplayFor(modelItem => item.ProductiveShiftHour)</td>
                            <td>@Html.DisplayFor(modelItem => item.Comments)</td>
                            <td style="text-align:center;"><a href="/Shift/Update/@item.Id"><i class="fa fa-edit" aria-hidden="true" style="font-size:20px;color:#4d4a45"></i></a> | <a href="#" onclick="Delete('@item.Id')"><i class="fa fa-trash" aria-hidden="true" style="font-size:20px;color:#4d4a45"></i></a></td>
                        </tr>
                        }
                </table>
            </div>
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }


            <div class="grid-table-footer">
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-default @prevDisabled"
                   style="background-color:#4d4a45; color:white;">
                    <i class="fa fa-angle-left fa-fw"></i>
                    Previous
                </a>
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-default @nextDisabled"
                   style="background-color:#4d4a45; color:white;">
                    <i class="fa fa-angle-right fa-fw"></i>
                    Next
                </a>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.row -->
</section>

<!-- DataTables -->
@*<script src="~/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>*@
@*<script src="~/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>*@



<!-- page script -->
<script>
        //$(function () {
        //    $('#example1').DataTable();
        //});
        function Delete(id){
            //alert(id)
            var txt;
            var r = confirm("Are you sure you want to Delete?");
            if (r == true) {

                $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("Delete", "Shift")',
                    data: {
                        id: id
                    },
                    error: function (result) {
                        alert("error");
                    },
                    success: function (result) {
                        if (result == true) {
                            var baseUrl = "/Index";
                            alert("Delete Succesful.");
                            window.location.reload();
                        }
                        else {
                            alert("Can't delete, May have data dependency !");
                        }

                    }
                });
            }
        }
</script>

<style>
    /*table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: left;
        padding: 8px;
    }


    tr:nth-child(even) {
        background-color: #e3d8c3;
    }*/







    table {
        border: 1px solid #e3d8c3;
        border-radius: 13px;
        border-spacing: 0;
    }

    /*table.roundedCorners td,
    table.roundedCorners th {
    border-bottom: 1px solid #e3d8c3;
    padding: 10px;
    }

    table.roundedCorners tr:last-child > td {
        border-bottom: none;
    }*/










    html {
        margin: 40px auto;
    }

    .btn-search {
        background: #286090;
        border-radius: 0;
        color: #fff;
        border-width: 1px;
        border-style: solid;
        border-color: #1c1c1c;
    }

        .btn-search:link, .btn-search:visited {
            color: #fff;
        }

        .btn-search:active, .btn-search:hover {
            background: blue;
            color: #ccc;
        }





    .btn-action {
        background: #286090;
        border-radius: 0;
        color: #fff;
        border-width: 1px;
        border-style: solid;
        border-color: #1c1c1c;
    }

        .btn-action:link, .btn-search:visited {
            color: #fff;
        }

        .btn-action:active, .btn-search:hover {
            background: blue;
            color: #ccc;
        }
</style>

LILI_FPMS/Views/Shift/Update.cshtml
@model LILI_IMS.Models.TblShiftSetup


@*<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>*@


<!-- Modal placeholder -->
<div id="modal-placeholder"></div>

<section class="content-header">
    @*<h1>
            Shift
        </h1>*@
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Shift Setup</li>
        <li class="active">Update Shift</li>
    </ol>
</section>
<!-- Main content -->
<section class="content container-fluid">
    <!-- Horizontal Form -->
    <div class="box box-info" style="border:1px solid; border-color:cadetblue; padding:10px">
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" asp-controller="Shift" method="post" asp-action="UpdateShift">
            <div class="box-body">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Shift Code</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" asp-for="ShiftCode" placeholder="Name" readonly value="@Model.ShiftCode">
                        <span asp-validation-for="ShiftCode"></span>

                    </div>

                    <label for="inputEmail3" class="col-sm-2 control-label">Shift Name</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" asp-for="ShiftName" placeholder="EmpId" value="@Model.ShiftName">
                        <span asp-validation-for="ShiftName"></span>
                    </div>
                </div>


                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Standard Shift Hour</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" asp-for="StandardShiftHour" placeholder="Standard Shift Hour" value="@Model.StandardShiftHour" onkeypress='return isNumberKey(event)'>
                        <span asp-validation-for="StandardShiftHour"></span>
                    </div>
                    <label for="inputEmail3" class="col-sm-2 control-label">Planned Down Change Time</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" asp-for="PlannedDownChangeTime" placeholder="Planned Down Change Time" value="@Model.PlannedDownChangeTime" onkeypress='return isNumberKey(event)'>
                        <span asp-validation-for="PlannedDownChangeTime"></span>
                    </div>
                </div>


                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Productive Shift Hour</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" asp-for="ProductiveShiftHour" placeholder="Standard Shift Hour" value="@Model.ProductiveShiftHour" onkeypress='return isNumberKey(event)'>
                        <span asp-validation-for="ProductiveShiftHour"></span>
                    </div>
                    <label for="inputEmail3" class="col-sm-2 control-label">Comments</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" asp-for="Comments" placeholder="Comments" value="@Model.Comments">
                        <span asp-validation-for="Comments"></span>
                    </div>
                </div>
                <div class="form-group">

                   
                        <label for="inputEmail3" class="col-sm-2 control-label">Shift Start Time</label>
                        <div class="col-sm-4">
                            <input type="time" asp-for="ShiftStartTime" class="form-control" placeholder="ShiftStartTime">
                        </div>
                   

                 
                        <label for="inputEmail3" class="col-sm-2 control-label">Shift End Time</label>
                        <div class="col-sm-4">
                            <input type="time" asp-for="ShiftEndTime" class="form-control" placeholder="ShiftEndTime">
                        </div>
                   

                </div>



                <input type="hidden" name="Id" value="@Model.Id" />
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <a class="btn btn-mini btn-primary" href='@Url.Content("/Shift/Index")'>Cancel</a>
                <button type="submit" class="btn btn-info pull-right">Update</button>
            </div>
            <!-- /.box-footer -->
        </form>
    </div>
    <!-- /.box -->
</section>

<script type="text/javascript">

    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode
        if (charCode > 31 && (charCode != 46 && (charCode < 48 || charCode > 57)))
            return false;
        return true;
    }

</script>