LILI_FPMS/Controllers/RequisitionController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using LILI_FPMS;
using LILI_FPMS.Models;
using LILI_IMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace LILI_IMS.Controllers
{
    [Authorize]
    public class RequisitionController : Controller
    {
        private readonly dbFormulationProductionSystemContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private static long GloablPlantId;
        public RequisitionController(dbFormulationProductionSystemContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            var plntid = _httpContextAccessor.HttpContext.Session.GetString("PlantId");
            if (!string.IsNullOrEmpty(plntid))
            {

                GloablPlantId = long.Parse(plntid);
            }
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "requisition_desc" : "";
            ViewData["ProductCodeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "productCode_desc" : "";
            ViewData["ProductNameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "productName_desc" : "";


            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var req = from s in _context.TblRequisition.Where(x=>x.PlantId== GloablPlantId)
                      from p in _context.View_Product
                      where s.ProductCode == p.ProductCode
                      select new TblRequisition
                      {
                          Id = s.Id,
                          RequisitionNo = s.RequisitionNo,
                          ProductCode = s.ProductCode,
                          ProductName = p.ProductName,
                          BatchNo = s.BatchNo,
                          NumberOfBatch = s.NumberOfBatch,
                          RequisitionDate = s.RequisitionDate,
                          IssueStatus = s.IssueStatus,
                      };

            if (!String.IsNullOrEmpty(searchString))
            {
                req = req.Where(s => s.RequisitionNo.Contains(searchString)
                                    || s.ProductCode.Contains(searchString)
                                    || s.ProductName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "requisition_desc":
                    req = req.OrderByDescending(s => s.RequisitionNo);
                    break;
                case "productCode_desc":
                    req = req.OrderByDescending(s => s.ProductCode);
                    break;
                case "productName_desc":
                    req = req.OrderByDescending(s => s.ProductCode);
                    break;

                default:
                    req = req.OrderByDescending(s => s.RequisitionNo);
                    break;
            }
            int pageSize = 10;
            return View(await PaginatedList<TblRequisition>.CreateAsync(req.AsNoTracking(), pageNumber ?? 1, pageSize));

            //return View(await employees.AsNoTracking().ToListAsync());
        }

        public ActionResult Create()
        {
            ////Generate Requisition No.---------Start
            //String sDate = DateTime.Now.ToString();
            //DateTime datevalue = (Convert.ToDateTime(sDate.ToString()));
            ////String dy = datevalue.Day.ToString("00");
            //String mn = datevalue.Month.ToString("00");
            //String yy = datevalue.Year.ToString().Substring(2, 2);
            //var requisitionNo = "REQ-" + yy + mn;
            //String maxId = "";
            //String maxNo = (from c in _context.TblRequisition.Where(c => c.RequisitionNo.Substring(0, 8) == requisitionNo).OrderByDescending(t => t.Id) select c.RequisitionNo.Substring(8, 3)).FirstOrDefault();
            //if (maxNo == null)
            //{
            //    maxId = "001";
            //}
            //else
            //{
            //    maxId = (Convert.ToInt16(maxNo) + 1).ToString("000");
            //}
            //requisitionNo = "REQ-" + yy + mn + maxId;

            ////Generate Requisition No.---------End

            TblRequisition entities = new TblRequisition();
            //entities.RequisitionNo = requisitionNo;
            entities.RequisitionNo = GenerateRequisitionNo();
            entities.RequisitionDate = DateTime.Now;
            return View(entities);
        }

        public string GenerateRequisitionNo()
        {
            //Generate Requisition No.---------Start
            String sDate = DateTime.Now.ToString();
            DateTime datevalue = (Convert.ToDateTime(sDate.ToString()));
            //String dy = datevalue.Day.ToString("00");
            String mn = datevalue.Month.ToString("00");
            String yy = datevalue.Year.ToString().Substring(2, 2);
            var requisitionNo = "REQ-" + yy + mn;
            String maxId = "";
            String maxNo = (from c in _context.TblRequisition.Where(c => c.RequisitionNo.Substring(0, 8) == requisitionNo).OrderByDescending(t => t.Id) select c.RequisitionNo.Substring(8, 3)).FirstOrDefault();
            if (maxNo == null)
            {
                maxId = "001";
            }
            else
            {
                maxId = (Convert.ToInt16(maxNo) + 1).ToString("000");
            }
            requisitionNo = "REQ-" + yy + mn + maxId;

            return requisitionNo;
            //Generate Requisition No.---------End
        }

        [HttpPost, ActionName("CreateRequisition")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRequisition(TblRequisition req)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    req.Iuser = User.Identity.Name;
                    req.Idate = DateTime.Now;
                    req.IssueStatus = "Pending";
                    req.PlantId = GloablPlantId;
                    req.RequisitionNo = GenerateRequisitionNo();
                    _context.Add(req);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    ViewData["Error"] = "Error message text.";
                    return View(req);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            //return View(student);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public bool Delete(int id)
        {
            try
            {
                
                TblRequisition req = _context.TblRequisition.Where(s => s.Id == id).First();
                if (IsEditableDeleteable(req.RequisitionNo) == true)
                {
                    _context.TblRequisitionDetail.RemoveRange(_context.TblRequisitionDetail.Where(d => d.RequisitionNo == req.RequisitionNo));
                    _context.TblRequisition.Remove(req);
                    _context.SaveChanges();
                    return true;
                }
                else
                {
                    return false;
                }
                
                //return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return false;
                //return RedirectToAction(nameof(Index));
            }
        }

        public ActionResult Update(int id)
        {
            Models.TblRequisition reqModel = new Models.TblRequisition();
            var dt = _context.TblRequisition.Where(s => s.Id == id).First();
            reqModel.Id = dt.Id;
            reqModel.RequisitionNo = dt.RequisitionNo;
            reqModel.RequisitionDate = dt.RequisitionDate;
            reqModel.BatchNo = dt.BatchNo;
            reqModel.NumberOfBatch = dt.NumberOfBatch;
            reqModel.BatchSize = 0;
            reqModel.StandardOutput = 0;
            reqModel.ProductCode = dt.ProductCode;
            reqModel.ProductName = _context.View_Product.Where(s => s.ProductCode == dt.ProductCode).FirstOrDefault().ProductName;
            reqModel.Comments = dt.Comments;
            reqModel.ExtOfRequisitionNo = dt.ExtOfRequisitionNo;
            reqModel.TblRequisitionDetail = _context.TblRequisitionDetail.Where(d => d.RequisitionNo == dt.RequisitionNo).ToList();
            reqModel.BOMId = dt.BOMId;

            var requisitionDetail = from reqDtl in _context.TblRequisitionDetail
                                 from mat in _context.View_Material
                                 where (reqDtl.RequisitionNo == dt.RequisitionNo && reqDtl.MaterialCode == mat.MaterialCode)
                                 orderby reqDtl.MaterialCode
                                select new TblRequisitionDetail
                                 {
                                     Id = reqDtl.Id,
                                     MaterialCode = reqDtl.MaterialCode,
                                     MaterialName = mat.MaterialName,

LILI_FPMS/Views/Requisition/Index.cshtml
@model PaginatedList<LILI_IMS.Models.TblRequisition>

<section class="content-header">
    @*<h1>
            Requisition
        </h1>*@
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Requisition</li>
    </ol>
</section>

@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-warning">
        <strong>Alert !</strong> @TempData["AlertMessage"]
    </div>
}



<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="box-body">
            <div class="col-xs-12">
                <div class="col-sm-11">
                    <form asp-action="Index" method="get">
                        <div class="form-actions no-color">
                            <div class="col-sm-12">
                                <div class="col-sm-6">
                                    <input type="text" name="SearchString" value="@ViewData["currentFilter"]" class="form-control" placeholder="Search for...">
                                </div>
                                <div class="col-sm-3">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-search" value="Search"><i class="fa fa-search fa-fw"></i>Search</button>
                                    </span>
                                </div>
                                <div class="col-sm-3">
                                    @*<a asp-action="Index">Back to Full List</a>*@
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
                <div class="col-sm-1">
                    <a class="btn btn-action" href="/Requisition/Create">
                        <i class="fa fa-plus fa-fw"></i>Add
                    </a>
                </div>
            </div>
            @*<table id="example1" class="table table-bordered table-striped roundedCorners">*@
            <div class="grid-table-header">
                <table id="RequisitionTable" class="table roundedCorners">
                    <thead>
                        <tr style="background-color:#6c7ae0; color:white; height:50px;">
                            <th style="text-align:center; width:7%">Id</th>
                            <th style="text-align:center; width:10%">
                                <a style="color:white;" asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Requisition No. <i class="fa fa-sort" style="font-size:20px;color:sandybrown;"></i></a>
                            </th>
                            <th style="text-align:center; width:10%">
                                <a style="color:white;" asp-action="Index" asp-route-sortOrder="@ViewData["ProductCodeSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Product Code <i class="fa fa-sort" style="font-size:20px;color:sandybrown"></i></a>
                            </th>
                            <th style="text-align:center; width:30%">
                                <a style="color:white;" asp-action="Index" asp-route-sortOrder="@ViewData["ProductNameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Product Name <i class="fa fa-sort" style="font-size:20px;color:sandybrown"></i></a>
                            </th>
                            <th style="text-align:center;  width:10%; display:none;">Batch No.</th>
                            <th style="text-align:center;  width:10%">Number of Batch</th>
                            <th style="text-align:center;  width:11%">Requisition Date</th>
                            <th style="text-align:center;  width:5%">Status</th>
                            <th style="text-align:center; width:10%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Id)</td>
                            <td>@Html.DisplayFor(modelItem => item.RequisitionNo)</td>
                            <td>@Html.DisplayFor(modelItem => item.ProductCode)</td>
                            <td>@Html.DisplayFor(modelItem => item.ProductName)</td>
                            <td style="display:none;">@Html.DisplayFor(modelItem => item.BatchNo)</td>
                            <td>@Html.DisplayFor(modelItem => item.NumberOfBatch)</td>
                            <td>@Html.DisplayFor(modelItem => item.RequisitionDate)</td>
                            <td style="color:blue; font-weight:bold">@Html.DisplayFor(modelItem => item.IssueStatus)</td>

                            <td style="text-align:center;"><a href="/Requisition/Update/@item.Id"><i class="fa fa-edit" aria-hidden="true" style="font-size:20px;color:#4d4a45"></i></a> | <a href="#" onclick="Delete('@item.Id')"><i class="fa fa-trash" aria-hidden="true" style="font-size:20px;color:#4d4a45"></i></a></td>
                        </tr>
                        }
                </table>
            </div>
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }


            <div class="grid-table-footer">
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-default @prevDisabled"
                   style="background-color:#4d4a45; color:white;">
                    <i class="fa fa-angle-left fa-fw"></i>
                    Previous
                </a>
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-default @nextDisabled"
                   style="background-color:#4d4a45; color:white;">
                    <i class="fa fa-angle-right fa-fw"></i>
                    Next
                </a>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.row -->
</section>

<!-- DataTables -->
@*<script src="~/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>*@
@*<script src="~/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>*@



<!-- page script -->
<script>
        //$(function () {
        //    $('#example1').DataTable();
        //});
        function Delete(id){
            //alert(id)
            var txt;
            var r = confirm("Are you sure you want to Delete?");
            if (r == true) {

                $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("Delete", "Requisition")',
                    data: {
                        id: id
                    },
                    error: function (result) {
                        alert("error");
                    },
                    success: function (result) {
                        if (result == true) {
                            var baseUrl = "/Index";
                            alert("Delete Succesful.");
                            window.location.reload();
                        }
                        else {
                            alert("Can't delete, May have data dependency !");
                        }

                    }
                });
            }
        }
</script>

<style>
    /*table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: left;
        padding: 8px;
    }


    tr:nth-child(even) {
        background-color: #e3d8c3;
    }*/







    table {
        border: 1px solid #e3d8c3;
        border-radius: 13px;
        border-spacing: 0;
    }

    /*table.roundedCorners td,
    table.roundedCorners th {
    border-bottom: 1px solid #e3d8c3;
    padding: 10px;
    }

    table.roundedCorners tr:last-child > td {
        border-bottom: none;
    }*/










    html {
        margin: 40px auto;
    }

    .btn-search {
        background: #286090;
        border-radius: 0;
        color: #fff;
        border-width: 1px;
        border-style: solid;
        border-color: #1c1c1c;
    }

        .btn-search:link, .btn-search:visited {
            color: #fff;
        }

        .btn-search:active, .btn-search:hover {
            background: blue;
            color: #ccc;
        }





    .btn-action {
        background: #286090;
        border-radius: 0;
        color: #fff;
        border-width: 1px;
        border-style: solid;
        border-color: #1c1c1c;
    }

        .btn-action:link, .btn-search:visited {
            color: #fff;
        }

        .btn-action:active, .btn-search:hover {
            background: blue;
            color: #ccc;
        }
</style>

LILI_FPMS/Views/Requisition/_MaterialSearchPartial.cshtml
@model LILI_IMS.Models.TblRequisitionDetail
<!-- Modal -->
<div class="modal fade" id="add-material-search" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#0c8599; color:white;">
                <h5 class="modal-title" id="addContactLabel">Add Material</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">                
                <form class="form-horizontal"  asp-action="MaterialSearchKey" style="padding-bottom:30px">
                    <div class="box-body">
                        <div class="form-group">
                            <div class="col-sm-10">
                                <input type="text" asp-for="MaterialCode" class="form-control" placeholder="Material Code">
                                <span asp-validation-for="MaterialCode"></span>
                            </div>
                            <div class="col-sm-2">
                                <a id="btnSearch" class="btn btn-primary">search</a>
                            </div>
                        </div>

                        <table id="tblProduct" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th style="width:10%">Id</th>
                                    <th style="width:45%">Material Code</th>
                                    <th style="width:45%">Material Name</th>
                                </tr>
                            </thead>
                            <tbody id="tblProductBody">
                            </tbody>
                        </table>                        
                    </div>
                </form>                

            </div>
            <div class="modal-footer" style="background-color:#0c8599; ">
                <button type="button" id="SetMaterial" class="btn btn-warning" data-dismiss="modal" >Ok</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>




<script type="text/javascript">

    

    $(document).ready(function () {
        $(window).keydown(function (event) {
            if (event.keyCode == 13) {
                event.preventDefault();

                var MaterialSearchKey = $("#MaterialCode").val();
                if (MaterialSearchKey != '') {
                    $.ajax({
                        type: "POST",
                        url: "/Requisition/SearchMaterial",
                        data: { MaterialSearchKey: MaterialSearchKey },
                        success: function (msg) {
                            console.log(msg);

                            $("#tblProduct #tblProductBody").empty();
                            var tr = '';
                            for (var i = 0; i < msg.length; i++) {
                                tr = $('<tr/>');
                                tr.append("<td>" + '<input name="MaterialCode" type="radio" value="' + msg[i].MaterialCode + '"></label>' + "</td>");
                                tr.append("<td>" + msg[i].MaterialCode + "</td>");
                                tr.append("<td>" + msg[i].MaterialName + "</td>");
                                $('#tblProduct #tblProductBody').append(tr);
                            }
                        },
                        error: function () {
                            //$('#ExpertiesId').val('');
                            //$('#ExpertArea').val('');
                            //$('#ExpertDesc').val('');
                        }
                    });
                }

               // return false;
            }
        });

        $('#btnSearch').on('click', function () {
            var MaterialSearchKey  = $("#MaterialCode").val();
            if (MaterialSearchKey  != '') {
                $.ajax({
                    type: "POST",
                    url: "/Requisition/SearchMaterial",
                    data: { MaterialSearchKey: MaterialSearchKey },
                    success: function (msg) {
                        console.log(msg);

                        $("#tblProduct #tblProductBody").empty();
                        var tr = '';
                        for (var i = 0; i < msg.length; i++) {
                            tr = $('<tr/>');
                            tr.append("<td>" + '<input name="MaterialCode" type="radio" value="' + msg[i].MaterialCode + '"></label>' + "</td>");
                            tr.append("<td>" + msg[i].MaterialCode + "</td>");
                            tr.append("<td>" + msg[i].MaterialName + "</td>");
                            $('#tblProduct #tblProductBody').append(tr);
                        }
                    },
                    error: function () {
                        //$('#ExpertiesId').val('');
                        //$('#ExpertArea').val('');
                        //$('#ExpertDesc').val('');
                    }
                });
            }
        });

        $('#SetMaterial').on('click', function () {
            var MaterialCode = $("input:checked").val();
            if (MaterialCode != '') {
                $.ajax({
                    type: "POST",
                    url: "/Requisition/SetMaterial",
                    data: { MaterialCode: MaterialCode },
                    success: function (msg) {
                        $('#MaterialCodeSearch').val('');
                        $('#MaterialNameSearch').val('');

                        for (var i = 0; i < msg.length; i++) {
                            $('#MaterialCodeSearch').val(msg[i].MaterialCode);
                            $('#MaterialNameSearch').val(msg[i].MaterialName);
                            $('#MaterialUnit').val(msg[i].BaseUnit);
                            $('#RequiredQty').val(msg[i].RequiredQty);
                        }
                    },
                    error: function () {
                        $('#MaterialCodeSearch').val('');
                        $('#MaterialNameSearch').val('');
                    }
                });
            }
        });

        });
       

</script>