LILI_FPMS/Controllers/QCController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using LILI_FPMS;
using LILI_FPMS.Models;
using LILI_IMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NPOI.SS.Formula.Eval;
using NPOI.SS.Formula.Functions;
using NPOI.SS.UserModel;
using Org.BouncyCastle.Ocsp;

namespace LILI_IMS.Controllers
{

    [Authorize]
    public class QCController : Controller
    {
        private readonly dbFormulationProductionSystemContext _context;
        private static string SECTION_CODE;

        private readonly IHttpContextAccessor _httpContextAccessor;
        private static long GlobalPlantId;
        public QCController(dbFormulationProductionSystemContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            var plntid = _httpContextAccessor.HttpContext.Session.GetString("PlantId");
            if (!string.IsNullOrEmpty(plntid))
            {
                GlobalPlantId = long.Parse(plntid);
            }
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["EmpIdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "empId_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            //var plans = from s in eFTestContext.TblMonthlyPlanning 
            //            from d in eFTestContext.TblMonthlyPlanningDetail
            //            where (s.PlanningNo == d.PlanningNo)
            //            select new {s.PlanningNo,s.Year,s.Month,d.Fgcode};

            var qc_data = from master in _context.TblQc.Where(master=>master.PlantId == GlobalPlantId)
                          from process in _context.TblProductionProcess.Where(process => process.PlantId == GlobalPlantId)
                          from bom in _context.View_BOM.Where(bom=> bom.IsActive=="Y")
                          from p in _context.View_Product
                          where( master.ProcessNo == process.ProcessNo && process.ProductCode == bom.ProductCode 
                          && bom.ProductCode== p.ProductCode)
                          select new TblQc {
                              Id = master.Id,
                              ProductCode = process.ProductCode,
                              ProductName = p.ProductName,
                              Qcno = master.Qcno,
                              Qcdate = master.Qcdate,
                              RequisitionNo =  master.RequisitionNo,
                              BatchNo =  process.BatchNo,
                              ProcessNo =  master.ProcessNo,
                              Qcqty =  master.Qcqty,
                              QcpassQty =  master.QcpassQty,
                              QcrejectQty =  master.QcrejectQty
                          };

            if (!String.IsNullOrEmpty(searchString))
            {
                qc_data = qc_data.Where(s => s.Qcno.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    qc_data = qc_data.OrderByDescending(s => s.Qcno);
                    break;
                case "empId_desc":
                    qc_data = qc_data.OrderByDescending(s => s.Qcno);
                    break;
                //case "Date":
                //    employees = employees.OrderBy(s => s.EnrollmentDate);
                //    break;
                //case "date_desc":
                //    employees = employees.OrderByDescending(s => s.EnrollmentDate);
                //    break;
                default:
                    qc_data = qc_data.OrderByDescending(s => s.Qcno);
                    break;
            }
            int pageSize = 7;


            return View(await PaginatedList<TblQc>.CreateAsync(qc_data.AsNoTracking(), pageNumber ?? 1, pageSize));

        }

        public ActionResult Create()
        {
            TblQc entities = new TblQc();

            List<SelectListItem> Year = new List<SelectListItem>();           

            entities.Idate = DateTime.Now;
            entities.Qcdate = DateTime.Now;
            entities.Qcno = GetAutoNumber();

            var businessCode = (from c in _context.TblUserWiseBusinessAndPlantCode
                                where c.PlantId == GlobalPlantId
                                select c.BusinessCode
                  ).FirstOrDefault();

            var productList = (from c in _context.View_Product select c).ToList();
            ViewBag.ListOfProduct = productList;

            List<TblQcparameterType> typeList = new List<TblQcparameterType>();
            typeList = (from c in _context.TblQcparameterType
                        select c).ToList();
            typeList.Insert(0, new TblQcparameterType { TypeCode = "0", TypeName = "Select Type" });
            ViewBag.ListOfType = typeList;

            //entities.TblQcdetails = (from para in eFTestContext.TblQcparameter
            //                                 select new TblQcdetails
            //                                 {
            //                                     Id = para.Id,
            //                                     QcparameterCode = para.QcparameterCode,
            //                                     QcparameterName = para.QcparameterName,
            //                                     QcparameterStandardValue = para.QcparameterStandardValue,
            //                                     QcparameterActualValue = null,
            //                                     Comments = null
            //                                 }).ToList();
            List<TblSection> sectionList= new List<TblSection>();
            //sectionList = _context.TblSection.ToList();
            sectionList = (from c in _context.TblSection.Where(c => c.PlantId == GlobalPlantId).OrderBy(c => c.Id) select c).ToList();
            sectionList.Insert(0, new TblSection { SectionCode = "0", SectionName = "Select Section" });
            ViewBag.ListOfSection = sectionList;
            return View(entities);
        }

        public string GetAutoNumber()
        {

            //Generate Requisition No.---------Start
            String sDate = DateTime.Now.ToString();
            DateTime datevalue = (Convert.ToDateTime(sDate.ToString()));
            //String dy = datevalue.Day.ToString("00");
            String mn = datevalue.Month.ToString("00");
            String yy = datevalue.Year.ToString().Substring(2, 2);
            var QCNo = "QC-" + yy + mn;
            String maxId = "";
            String maxNo = (from c in _context.TblQc.Where(c => c.Qcno.Substring(0, 7) == QCNo).OrderByDescending(t => t.Id) select c.Qcno.Substring(7, 3)).FirstOrDefault();
            if (maxNo == null)
            {
                maxId = "001";
            }
            else
            {
                maxId = (Convert.ToInt16(maxNo) + 1).ToString("000");
            }
            QCNo = "QC-" + yy + mn + maxId;

            return QCNo;

        }

        [HttpPost, ActionName("CreateQC")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateQC(TblQc qc_data)
        //[Bind("EnrollmentDate,FirstMidName,LastName")] Student student)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    //var qc_entity = new TblQc
                    //{
                    //    Qcno = qc_data.Qcno,
                    //    Qcdate = qc_data.Qcdate,
                    //    RequisitionNo = qc_data.RequisitionNo,
                    //    ProcessNo = qc_data.ProcessNo,
                    //    Qcqty = qc_data.Qcqty,
                    //    QcpassQty = qc_data.QcpassQty,
                    //    QcrejectQty = qc_data.QcrejectQty,
                    //    Comments = qc_data.Comments,
                    //    Iuser = User.Identity.Name,
                    //    Idate = DateTime.Now
                    //};
                    //_context.TblQc.Add(qc_entity);
                    //await _context.SaveChangesAsync();


                    //if (qc_data.TblQcdetails != null)
                    //{
                    //    foreach (var item in qc_data.TblQcdetails.ToList())
                    //    {
                    //        TblQcdetails itemDetail = new TblQcdetails();
                    //        itemDetail.Qcno = qc_data.Qcno;
                    //        itemDetail.QcparameterCode = item.QcparameterCode;
                    //        itemDetail.QcparameterActualValue = item.QcparameterActualValue;
                    //        itemDetail.Comments = item.Comments;
                    //        await _context.AddAsync(itemDetail);
                    //    }
                    //}
                    //await _context.SaveChangesAsync();
                    //TempData["Success"] = "Success message text.";


                    qc_data.Iuser = User.Identity.Name;
                    qc_data.Idate = DateTime.Now;
                    qc_data.PlantId = GlobalPlantId;
                    qc_data.Qcno = GetAutoNumber();
                    _context.Add(qc_data);

LILI_FPMS/Views/QC/Index.cshtml
@model PaginatedList<LILI_IMS.Models.TblQc>



<section class="content-header">
    @*<h1>
            Employee
        </h1>*@
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">QC Information</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">


    <div class="row">

        <div class="box-body">
            <div class="col-xs-12">
                <div class="col-sm-11">
                    <form asp-action="Index" method="get">
                        <div class="form-actions no-color">
                            <div class="col-sm-12">
                                <div class="col-sm-6">
                                    <input type="text" name="SearchString" value="@ViewData["currentFilter"]" class="form-control" placeholder="Search for...">
                                </div>
                                <div class="col-sm-3">
                                    <span class="input-group-btn">
                                        @*<input  value="Search" class="btn btn-default" style="background-color:#4d4a45; color:white;" />*@
                                        <button type="submit" class="btn btn-search" value="Search"><i class="fa fa-search fa-fw"></i>Search</button>
                                    </span>
                                </div>
                                <div class="col-sm-3">
                                    @*<a asp-action="Index">Back to Full List</a>*@
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
                <div class="col-sm-1">
                    <a class="btn btn-action" href="/QC/Create">
                        <i class="fa fa-plus fa-fw"></i>Add
                    </a>
                </div>
            </div>
            @*<table id="example1" class="table table-bordered table-striped roundedCorners">*@
            <div class="grid-table-header">
                <table id="tblPlan" class="table roundedCorners">
                    <thead>
                        <tr style="background-color:#6c7ae0; color:white; height:50px;">
                            <th style="text-align:center;  width:5%">Code</th>
                            <th style="text-align:center;  width:10%">Name</th>
                            <th style="text-align:center; width:10%">QC No.</th>
                            <th style="text-align:center;  width:10%">QC Date</th>
                            <th style="text-align:center;  width:10%">Requisition No.</th>
                            <th style="text-align:center;  width:10%">Batch No.</th>
                            <th style="text-align:center;  width:10%">Process No.</th>
                            <th style="text-align:center;  width:10%">QC Qty</th>
                            <th style="text-align:center;  width:10%">QC Pass Qty</th>
                            <th style="text-align:center;  width:10%">QC Reject Qty</th>
                            <th style="text-align:center; width:5%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.ProductCode)</td>
                            <td>@Html.DisplayFor(modelItem => item.ProductName)</td>
                            <td>@Html.DisplayFor(modelItem => item.Qcno)</td>
                            <td>@Html.DisplayFor(modelItem => item.Qcdate)</td>
                            <td>@Html.DisplayFor(modelItem => item.RequisitionNo)</td>
                            <td>@Html.DisplayFor(modelItem => item.BatchNo)</td>
                            <td>@Html.DisplayFor(modelItem => item.ProcessNo)</td>
                            <td>@Html.DisplayFor(modelItem => item.Qcqty)</td>
                            <td>@Html.DisplayFor(modelItem => item.QcpassQty)</td>
                            <td>@Html.DisplayFor(modelItem => item.QcrejectQty)</td>
                            <td style="text-align:center;"><a href="/QC/Update/@item.Id"><i class="fa fa-edit" aria-hidden="true" style="font-size:20px;color:#4d4a45"></i></a> | <a href="#" onclick="Delete('@item.Id')"><i class="fa fa-trash" aria-hidden="true" style="font-size:20px;color:#4d4a45"></i></a></td>
                        </tr>
                        }
                </table>
            </div>
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }


            <div class="grid-table-footer">
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-default @prevDisabled"
                   style="background-color:#4d4a45; color:white;">
                    <i class="fa fa-angle-left fa-fw"></i>
                    Previous
                </a>
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-default @nextDisabled"
                   style="background-color:#4d4a45; color:white;">
                    <i class="fa fa-angle-right fa-fw"></i>
                    Next
                </a>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.row -->
</section>

<!-- DataTables -->
@*<script src="~/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>*@
@*<script src="~/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>*@



<!-- page script -->
<script>
        //$(function () {
        //    $('#example1').DataTable();
        //});
        function Delete(id){
            //alert(id)
            var txt;
            var r = confirm("Are you sure you want to Delete?");
            if (r == true) {

                $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("Delete", "QC")',
                    data: {
                        id: id
                    },
                    error: function (result) {
                        alert("error");
                    },
                    success: function (result) {
                        if (result == true) {
                            var baseUrl = "/Index";
                            alert("Delete Succesful.");
                            window.location.reload();
                        }
                        else {
                            alert("Can't delete, May have data dependency !");
                        }

                    }
                });
            }
        }
</script>

<style>
    /*table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: left;
        padding: 8px;
    }


    tr:nth-child(even) {
        background-color: #e3d8c3;
    }*/







    table {
        border: 1px solid #e3d8c3;
        border-radius: 13px;
        border-spacing: 0;
    }

    /*table.roundedCorners td,
    table.roundedCorners th {
    border-bottom: 1px solid #e3d8c3;
    padding: 10px;
    }

    table.roundedCorners tr:last-child > td {
        border-bottom: none;
    }*/










    html {
        margin: 40px auto;
    }

    .btn-search {
        background: #286090;
        border-radius: 0;
        color: #fff;
        border-width: 1px;
        border-style: solid;
        border-color: #1c1c1c;
    }

        .btn-search:link, .btn-search:visited {
            color: #fff;
        }

        .btn-search:active, .btn-search:hover {
            background: blue;
            color: #ccc;
        }





    .btn-action {
        background: #286090;
        border-radius: 0;
        color: #fff;
        border-width: 1px;
        border-style: solid;
        border-color: #1c1c1c;
    }

        .btn-action:link, .btn-search:visited {
            color: #fff;
        }

        .btn-action:active, .btn-search:hover {
            background: blue;
            color: #ccc;
        }
</style>

LILI_FPMS/Views/QC/_RequisitionAreaPartial.cshtml
@model List<LILI_IMS.Models.GetSearchRequisitionList>
<!-- Modal -->
<div class="modal fade" id="add-Requisition" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true" >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#0c8599; color:white;">
                <h5 class="modal-title" id="addContactLabel">Add Requisition</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">                
                <form class="form-horizontal"  asp-action="SearchRequisition" style="padding-bottom:30px">
                    <div class="box-body">
                        <div class="form-group">
                           @* <div class="col-sm-10">
                                <input type="text" asp-for="RequisitionNo" class="form-control" placeholder="RequisitionNo">
                                <span asp-validation-for="RequisitionNo"></span>
                            </div>*@

                             <div class="col-sm-10">
                                <input type="text" Id="RequisitionNo" class="form-control" placeholder="RequisitionNo">
                                
                            </div>
                            <div class="col-sm-2">
                                <a id="btnSearch" class="btn btn-primary">search</a>
                            </div>
                        </div>

                        <table id="tblRequisitionMaster" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th style="width:10%">select</th>
                                    <th style="width:10%">RequisitionNo</th>
                                    <th style="width:45%">Code</th>
                                    <th style="width:45%">Name</th>
                                </tr>
                            </thead>
                            <tbody id="tblRequisitionSearchBody" class="js_tbl_body">
                                @{
                                    int i = 0; @*To make unique Id*@
                                    foreach (var item in Model)
                                    {
                                                                                @*@Html.HiddenIndexerInputForModel()*@
                                        var index = i;
                                                                                <tr>
                                                                                    <td style="display:none"><input name='tblProductDetail.Index' type="hidden" value=@index /></td>
                                                                                    <td>@Html.RadioButtonFor(modelItem => item.RequisitionNo, item.RequisitionNo)</td>
                                                                                    <td>@Html.DisplayFor(modelItem => item.RequisitionNo, new { @id = "RequisitionNo_" + i })</td>
                                                                                    <td>@Html.DisplayFor(modelItem => item.ProductCode, new { @id = "ProductCode_" + i })</td>
                                                                                    <td>@Html.DisplayFor(modelItem => item.ProductName, new { @id = "ProductName_" + i })</td>
                                                                                    @*<td><input type="button" value="Remove" onClick="$(this).closest('tr').remove();"></td>*@
                                                                                </tr>
                                        i++;
                                    }
                                }
                            </tbody>
                        </table>                        
                    </div>
                </form>                

            </div>
            <div class="modal-footer" style="background-color:#0c8599; ">
                <button type="button" id="SetRequisitionInfo" class="btn btn-warning" data-dismiss="modal" >Ok</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                @*<button type="button" id="SetExperties" class="btn btn-primary" data-save="modal">Ok</button>*@
            </div>
        </div>
    </div>
</div>




<script type="text/javascript">

    

    $(document).ready(function () {
        $(window).keydown(function (event) {
            if (event.keyCode == 13) {
                event.preventDefault();

                var RequisitionNo = $("#RequisitionNo").val();
                if (RequisitionNo != '') {
                    $.ajax({
                        type: "POST",
                        url: "/QC/SearchRequisition",
                        data: { RequisitionNo: RequisitionNo },
                        success: function (msg) {
                            console.log(msg);

                            $("#tblRequisitionMaster #tblRequisitionSearchBody").empty();
                            var tr = '';
                            for (var i = 0; i < msg.length; i++) {
                                tr = $('<tr/>');
                                tr.append("<td>" + '<input name="RequisitionNo" type="radio" value="' + msg[i].RequisitionNo + '"></label>' + "</td>");
                                tr.append("<td>" + msg[i].RequisitionNo + "</td>");
                                tr.append("<td>" + msg[i].ProductCode + "</td>");
                                tr.append("<td>" + msg[i].ProductName + "</td>");
                                $("#tblRequisitionMaster #tblRequisitionSearchBody").append(tr);
                            }
                        },
                        error: function () {
                            //$('#ExpertiesId').val('');
                            //$('#ExpertArea').val('');
                            //$('#ExpertDesc').val('');
                        }
                    });
                }

               // return false;
            }
        });

        $('#btnSearch').on('click', function () {
            var RequisitionNo = $("#RequisitionNo").val();
            //if (RequisitionNo != '') {
                $.ajax({
                    type: "POST",
                    url: "/QC/SearchRequisition",
                    data: { RequisitionNo: RequisitionNo },
                    success: function (msg) {
                        console.log(msg);

                        $("#tblRequisitionMaster #tblRequisitionSearchBody").empty();
                        var tr = '';
                        for (var i = 0; i < msg.length; i++) {
                            tr = $('<tr/>');
                            tr.append("<td>" + '<input name="RequisitionNo" type="radio" value="' + msg[i].RequisitionNo + '"></label>' + "</td>");
                            tr.append("<td>" + msg[i].RequisitionNo + "</td>");
                            tr.append("<td>" + msg[i].ProductCode + "</td>");
                            tr.append("<td>" + msg[i].ProductName + "</td>");
                            $("#tblRequisitionMaster #tblRequisitionSearchBody").append(tr);
                        }
                    },
                    error: function () {
                        //$('#ExpertiesId').val('');
                        //$('#ExpertArea').val('');
                        //$('#ExpertDesc').val('');
                    }
                });
            //}
        });

        $('#SetRequisitionInfo').on('click', function () {
            var RequisitionNo = $("input:checked").val();
            if (RequisitionNo != '') {
                $.ajax({
                    type: "POST",
                    url: "/QC/SetRequisitionInfomation",
                    data: { RequisitionNo: RequisitionNo },
                    success: function (msg) {
                        $('#js_requisition_no').val('');
                        $('#BatchNo').val('');
                        $('#ProductCode').val('');
                        $('#ProductName').val('');
                        $('#Unit').val('');
                        $('#BatchSize').val(''); 
                        $('#AvailableStock').val();
                        $('#FGQCQtyConversionFactor').val();

                        for (var i = 0; i < msg.length; i++) {
                            console.log(msg[i].RequisitionNo);
                            $('#js_requisition_no').val(msg[i].RequisitionNo);
                            $('#BatchNo').val(msg[i].BatchNo);
                            $('#ProductCode').val(msg[i].ProductCode);
                            $('#ProductName').val(msg[i].ProductName);
                            $('#Unit').val(msg[i].PackSize);
                            $('#BatchSize').val(msg[i].BatchSize);
                            $('#AvailableStock').val(msg[i].AvailableStock);
                            $('#FGQCQtyConversionFactor').val(msg[i].ConversionValue);
                        }                        
                    },
                    error: function () {
                        $('#js_requisition_no').val('');
                        $('#BatchNo').val('');
                        $('#ProductCode').val('');
                        $('#ProductName').val('');
                        $('#Unit').val('');
                        $('#BatchSize').val('');
                        $('#AvailableStock').val();
                        $('#FGQCQtyConversionFactor').val();
                    }
                });

                $.ajax({
                    type: "POST",
                    url: "/QC/GetProcessNumber",
                    data: { RequisitionNo: RequisitionNo },
                    success: function (result) {

                        console.log(result);    
                        var formoption = "<option value='" + 0 + "'>" + "-- Select Process --" + "</option>";
                        for (var i = 0; i < result.length; i++) {
                            if (result[i].ProcessNo != '') {
                                if (result[i].ProcessNo != undefined) {
                                    formoption += "<option value='" + result[i].ProcessNo + "'>" + result[i].ProcessNo + "</option>";
                                }
                            }
                        }
                        $('#ProcessNo').html(formoption);
                    },
                    error: function () {
                       
                    }
                });               

            }
        });

        $('#ProcessNo').on('change', function () {
            //alert(this.value);
            $.ajax({
                type: "POST",
                url: "/QC/GetQCQuantity",
                data: { ProcessNo: this.value },
                success: function (result) {
                    $('#Qcqty').val('');    
                    for (var i = 0; i < result.length; i++) {
                        $('#FGQCQtyBeforeConversion').val((parseFloat(result[i].ProductionQty) - parseFloat(result[i].QCReferenceSampleQty) - parseFloat(result[i].LumpQty)));
                        //$('#Qcqty').val(result[i].ProductionQty);
                        var conversionFactor = $('#FGQCQtyConversionFactor').val();
                        $('#Qcqty').val(((parseFloat(result[i].ProductionQty) - parseFloat(result[i].QCReferenceSampleQty) - parseFloat(result[i].LumpQty)) / parseFloat(conversionFactor)).toFixed(5));
                        $('#SFGQcqty').val(result[i].SFGProductionQty);
                        $('#BatchNo').val(result[i].BatchNo);
                        
                    }
                },
                error: function () {

                }
            });

            var productCode = $("#ProductCode").val();
            GetTypeWiseQCParameter(productCode);
        });


       

    });
       

</script>