LILI_FPMS/Controllers/ProductWiseSectionSetupController.cs
using LILI_FPMS.Models;
using LILI_IMS;
using LILI_IMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace LILI_FPMS.Controllers
{
    [Authorize]
    public class ProductWiseSectionSetupController : Controller
    {
        private readonly dbFormulationProductionSystemContext _context;

        private readonly IHttpContextAccessor _httpContextAccessor;
        private static long GlobalPlantId;
        public ProductWiseSectionSetupController(dbFormulationProductionSystemContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            var plntid = _httpContextAccessor.HttpContext.Session.GetString("PlantId");
            if (!string.IsNullOrEmpty(plntid))
            {
                GlobalPlantId = long.Parse(plntid);
            }
        }
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["ProductCodeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "productCode_desc" : "";
            ViewData["ProductNameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "productName_desc" : "";
       
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var pross = from s in _context.TblProductWiseSectionSetup.Where(s=>s.PlantId==GlobalPlantId)
                        select new Models.TblProductWiseSectionSetup
                        {
                            Id = s.Id,
                            ProductCode= s.ProductCode=="0" || s.ProductCode == null?"All": s.ProductCode,
                            ProductName= s.ProductName=="0" || s.ProductCode == null? "All": s.ProductName,
                            PlantId=s.PlantId,
                        };

            if (!String.IsNullOrEmpty(searchString))
            {
                pross = pross.Where(s => s.ProductCode.Contains(searchString)
                                    || s.ProductName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "productCode_desc":
                    pross = pross.OrderByDescending(s => s.ProductCode);
                    break;
                case "productName_desc":
                    pross = pross.OrderByDescending(s => s.ProductName);
                    break;
            }
            int pageSize = 10;
            return View(await PaginatedList<TblProductWiseSectionSetup>.CreateAsync(pross.AsNoTracking(), pageNumber ?? 1, pageSize));
            //return View();
        }
        public ActionResult Create()
        {
            var model = new TblProductWiseSectionSetup();
               var list = new List<SelectListItem> {
               new SelectListItem{ Text="1", Value = "1", Selected = true },
               new SelectListItem{ Text="2", Value = "2" },
               new SelectListItem{ Text="3", Value = "3" },
               new SelectListItem{ Text="4", Value = "4"},
               new SelectListItem{ Text="5", Value = "5"},
            };
            var sectionList = from c in _context.TblSection.Where(c => c.PlantId == GlobalPlantId).OrderBy(c => c.Id)
                              select
                              new TblSection
                              {
                                  SectionCode = c.SectionCode,
                                  SectionName = c.SectionName,
                              };
            ViewBag.SectionList = sectionList.ToList();
            ViewBag.SelectionList=list;
            model.PlantId = GlobalPlantId;
            return View(model);
        }
        [HttpPost,ActionName("CreateProductWiseSection")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProductWiseSection(TblProductWiseSectionSetup prodwisesetup) {
            try {
                if (ModelState.IsValid)
                {
                    //if (prodwisesetup.ProductCode == null || prodwisesetup.ProductCode == "")
                    //{
                    //    prodwisesetup.ProductCode = "All";
                    //    prodwisesetup.ProductName = "All";
                    //}
                    prodwisesetup.Iuser = User.Identity.Name;
                    prodwisesetup.Idate = DateTime.Now;
                    prodwisesetup.PlantId= GlobalPlantId; 
                    _context.Add(prodwisesetup);
                    await _context.SaveChangesAsync();
                    TempData["msg"] =  "Data Save Successful!";
                }
                else {
                    var errors = ModelState
                        .Where(x => x.Value.Errors.Count > 0)
                        .Select(x => new { x.Key, x.Value.Errors })
                        .ToArray();
                    TempData["msg"] = "Error Model Data!";
                    return View(nameof(Index));
                }
            }
            catch (Exception ex) {
              
                TempData["msg"] = "Unsuccessful To Save Data";
                
            }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Update(int id)
        {
            TblProductWiseSectionSetup model = new TblProductWiseSectionSetup();
            var data = _context.TblProductWiseSectionSetup.Where(x => x.Id == id).First();
            var detalTbl= from c in _context.TblProductWiseSectionSetupDetail
                          from s in _context.TblSection
                          where c.ProductSectionSetupId== id && c.Section == s.SectionCode 
                          select new TblProductWiseSectionSetupDetail { 
                            Id = c.Id,
                            ProductSectionSetupId = c.ProductSectionSetupId,
                            Section=c.Section,
                            SectionName=s.SectionName,
                            Sequence=c.Sequence,
                            Comments=c.Comments,
                            IsQcrequired=c.IsQcrequired,
                            IsSetupCompleted=c.IsSetupCompleted,

                          };
            model.Id = data.Id;
            model.ProductCode = data.ProductCode;
            model.ProductName = data.ProductName;
            model.PlantId= data.PlantId;
            model.tblProductWiseSectionSetupDetails=detalTbl.ToList();
            var list = new List<SelectListItem> {
               new SelectListItem{ Text="1", Value = "1", Selected = true },
               new SelectListItem{ Text="2", Value = "2" },
               new SelectListItem{ Text="3", Value = "3" },
               new SelectListItem{ Text="4", Value = "4"},
               new SelectListItem{ Text="5", Value = "5"},
            };
            var sectionList = from c in _context.TblSection.Where(c => c.PlantId == GlobalPlantId).OrderBy(c => c.Id)
                              select
                              new TblSection
                              {
                                  SectionCode = c.SectionCode,
                                  SectionName = c.SectionName,
                              };
            ViewBag.SectionList = sectionList.ToList();
            ViewBag.SelectionList = list;

          
            return View(model);
        }
        [HttpPost, ActionName("UpdateProductWiseSection")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateProductWiseSection(int id, TblProductWiseSectionSetup prodwisesetup) {
                if (id != prodwisesetup.Id)
                {
                    return NotFound();
                }
            using (var transaction = await _context.Database.BeginTransactionAsync())
            {

                try
                {
                    var productwisesetuptoupdate = await _context.TblProductWiseSectionSetup.FirstOrDefaultAsync(p => p.Id == id);
                    productwisesetuptoupdate.Euser = User.Identity.Name;
                    productwisesetuptoupdate.Edate = DateTime.Now;
                    if (
                        await TryUpdateModelAsync<TblProductWiseSectionSetup>(
                        productwisesetuptoupdate,
                        "",
                        s => s.Euser,
                        s => s.Edate
                        )) ;
                    var productwisedetailtoRemove = _context.TblProductWiseSectionSetupDetail.Where(p => p.ProductSectionSetupId == id);
                    if (productwisedetailtoRemove != null)
                    {
                        _context.TblProductWiseSectionSetupDetail.RemoveRange(productwisedetailtoRemove);
                    }

                    if (prodwisesetup.tblProductWiseSectionSetupDetails != null)
                    {
                        foreach (var item in prodwisesetup.tblProductWiseSectionSetupDetails)
                        {
                            TblProductWiseSectionSetupDetail prodwisedetail = new TblProductWiseSectionSetupDetail();
                            prodwisedetail.ProductSectionSetupId = prodwisesetup.Id;
                            prodwisedetail.Section = item.Section;
                            prodwisedetail.Sequence = item.Sequence;
                            prodwisedetail.Comments = item.Comments;
                            prodwisedetail.IsQcrequired = item.IsQcrequired;
                            prodwisedetail.IsSetupCompleted = item.IsSetupCompleted;

LILI_FPMS/Views/ProductWiseSectionSetup/Create.cshtml
@model LILI_FPMS.Models.TblProductWiseSectionSetup

<div id="modal-placeholder"></div>

@if (TempData["msg"] != null && TempData["msg"] != "")
{
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-success" role="alert">
                @TempData["msg"]
            </div>
        </div>
    </div>
}




<section class="content-header">

    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Product Wise Section Setup</li>
        <li class="active">Add Section to Product</li>
    </ol>
</section>

<section class="content container-fluid">

    <div class="card" style="border:1px solid; border-color:cadetblue; padding:1vh">

        <form class="form-horizontal" asp-controller="ProductWiseSectionSetup" method="post" asp-action="CreateProductWiseSection" onsubmit="return SetupCheck()">
         

            <div class="card-body">
                <div class="col-md-12">
               
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Plant id</label>
                            <div class="col-sm-2">
                                <input type="hidden" name="Id" value="@Model.Id" />
                                <input type="text" asp-for="PlantId" id="PlantId" class="form-control" placeholder="Plant Id" readonly="readonly">
                                <span asp-validation-for="PlantId"></span>
                            </div>
                        </div>
                        <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Product Code</label>
                        <div class="col-sm-2">
                            <input type="text" asp-for="ProductCode" id="ProductCode" class="form-control" placeholder="Product Code" readonly="readonly">
                            <span asp-validation-for="ProductCode"></span>
                        </div>
                        <div class="col-sm-1 controls">
                            <button type="button" class="btn btn-info" data-toggle="ajax-modal" data-target="#add-product" data-url="@Url.Action("addProduct")">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </div>
                        <label for="inputEmail3" class="col-sm-1 control-label">Product Name</label>
                        <div class="col-sm-2">
                            <input type="text" Id="ProductName" asp-for="ProductName" class="form-control" placeholder="Product Name" readonly>
                        </div>
                    </div>

                        <div class="form-group">
                            <label name="Section" class="col-sm-2 control-label">Section</label>
                            <div class="col-sm-2">
                            <select name="Section" id="Section" class="form-control">
                                    @foreach (var item in ViewBag.SectionList)
                                {
                                        <option value="@item.SectionCode">@item.SectionName</option>
                                }
                            </select>
                                <span for="Section"></span>
                            </div>

                            <label name="Sequence" class="col-sm-1 col-sm-offset-1 control-label">Sequence</label>
                            <div class="col-sm-2">
                                <select name="Sequence" id="Sequence" class="form-control">
                                    @foreach (var item in ViewBag.SelectionList)
                                    {
                                        <option value="@item.Value">@item.Text</option>
                                    }
                                </select>
                                <span for="Section"></span>
                            </div>
                        </div>

 

                        <div class="form-group">
                            <label name="Section" class="col-sm-1 col-sm-offset-1 control-label">Comments</label>
                            <div class="col-sm-2">
                            <textarea class="form-control" rows="5" name="Comments" id="comments" style="width:90rem"></textarea>
                            </div>
                       
                        </div>

                         <div class="form-group">
                            <div class="col-sm-2 col-sm-offset-2">
                               <button type="button" id="addnewrowbtn" class="btn btn-mini btn-primary" onclick="AddNewRow()">Add</button>
                            </div>

                            <div class="col-sm-1 ">
                            <input type="checkbox"  id="isQCrequired">
                            <input type="hidden" id="checkboxValue" value="yes">
                            <label for=""> QC Required</label>
                            </div>

                            <div class="col-sm-2 ">
                                <input type="checkbox" id="isSetupCompleted">
                                <input type="hidden" id="checkboxValue1" value="no">
                                <label for="">Completed Setup</label>
                            </div>
                       </div>
                     </div>
                    <div class="col-md-12">
                    <div class="card" style="border:1px solid; border-color:cadetblue; padding:0.5vh; margin:0.5vh">

                            <table class="table table-bordered">
                            <thead>
                                <th style="width:7%; display:none">Prdouct Code</th>
                                <th style="width:15%;display:none">Prdouct Name</th>
                                <th style="width:7%">Section</th>
                                <th style="width:7%">Section Name</th>
                                <th style="width:7%">Sequence</th>
                                <th style="width:7%">QC Required</th> 
                                <th style="width:7%">Setup Completed</th>
                                <th style="width:20%">Comments</th>
                                <th style="width:7%">Action</th>
                            </thead>
                            <tbody id="tblProductWiseSectionSetupDetials">

                            </tbody>
                        </table>
                    </div>

                </div>

            


            </div>
            
            <div class="card-footer" style="">

                <a class="btn btn-mini btn-primary" href='@Url.Content("/ProductWiseSectionSetup/Index")'>Cancel</a>

             
                <button type="submit" class="btn btn-mini btn-primary pull-right">Create</button>

            </div>
                       
        </form>
       
    </div>
   
</section>

<script type="text/javascript">
    $(document).ready(function(){
        //$(".select2").select2();
        $("#isQCrequired").attr("Checked", true);
    });

    $("#isQCrequired ").change(function () {
        if ($(this).is(':checked')) {
            $("#checkboxValue").val("yes");
            console.log($("#checkboxValue").val());
        }
        else {
            $("#checkboxValue").val("no");
            console.log($("#checkboxValue").val());
        }
    });  
    $("#isSetupCompleted ").change(function () {
        if ($(this).is(':checked')) {
            $("#checkboxValue1").val("yes");

            console.log($("#checkboxValue").val());
        }
        else {
            $("#checkboxValue1").val("no");
            console.log($("#checkboxValue1").val());

        }
    });
    function AddNewRow()
    {
        var productCode=$("#ProductCode").val();
   
            
      
        var productName = $("#ProductName").val();
        var section= $("#Section").val();
        var sectionName = $("#Section option:selected").text();
        var sequence = $("#Sequence").val();
        var isQcrequired = $("#checkboxValue").val();
        var isSetupCompleted = $("#checkboxValue1").val();
        var comment= $("#comments").val();

        if (isSetupCompleted == "yes") {
            $("#addnewrowbtn").prop("disabled", true);
        }
        @{
        Model.tblProductWiseSectionSetupDetails.Add(new LILI_FPMS.Models.TblProductWiseSectionSetupDetail());
        }

                var index = $("#tblProductWiseSectionSetupDetials").children("tr").length;
        
        //var indexCell = "<td style='display:none'><input name='TblProductWiseSectionSetupDetails.Index' type='hidden' value='" + index + "' /></td>";
        //var idCell = "<td style='display:none'> <input id='TblProductWiseSectionSetupDetails" + index + "_Id' name='TblProductWiseSectionSetupDetails[" + index + "].Id' type='text' value='" + parseInt(index + 1) + "' /></td>";
        var productCodeCell = "<td style='display:none'><input style='border:none'  type='text' value='" + productCode + "' readonly/></td>";
        var productNameCell = "<td  style='display:none'><input style='border:none' type='text' value='" + productName + "' readonly/></td>";

        var sectionCell =      "<td><input style='text-align:left; width:100%; border: none;' id='TblProductWiseSectionSetupDetails" + index + "_Section' name='TblProductWiseSectionSetupDetails[" + index + "].Section' type='text' value='" + section + "' /></td>";
        var sectionNameCell = "<td><input style='text-align:left; width:100%; border: none;' id='TblProductWiseSectionSetupDetails" + index + "_SectionName' name='TblProductWiseSectionSetupDetails[" + index + "].SectionName' type='text' value='" + sectionName + "' /></td>";
        var sequnceCell =      "<td><input style='text-align:right; width:100%; border: none;' id='TblProductWiseSectionSetupDetails" + index + "_Sequence' name='TblProductWiseSectionSetupDetails[" + index + "].Sequence' type='text' value='" + sequence + "' /></td>";
        var isQcrequiredCell = "<td><input style='text-align:left; width:100%; border: none;' id='TblProductWiseSectionSetupDetails" + index + "_IsQcrequired' name='TblProductWiseSectionSetupDetails[" + index + "].IsQcrequired' type='text' value='" + isQcrequired + "' /></td>";
        var isSetupCompletedCell = "<td><input style='text-align:left; width:100%; border: none;' id='TblProductWiseSectionSetupDetails" + index + "_IsQcrequired' name='TblProductWiseSectionSetupDetails[" + index + "].IsSetupCompleted' type='text' value='" + isSetupCompleted + "' /></td>";

        var commentsCell =     "<td><input style='text-align:left; width:100%; border: none;' id='TblProductWiseSectionSetupDetails" + index + "_Comments' name='TblProductWiseSectionSetupDetails[" + index + "].Comments' type='text' value='" + comment + "' /></td>";
        var removeCell =       "<td><input id='addRow' type='button' class='btn btn-sm btn-danger' value='X' onclick='removeProductWiseSectionSetupDetial(" + index + ");' /></td>";

        var newRow = "<tr id='tblProductWiseSectionSetupDetials" + index + "'>" + productCodeCell + productNameCell + sectionCell + sectionNameCell + sequnceCell + isQcrequiredCell + isSetupCompletedCell + commentsCell + removeCell + "</tr>";
        console.log(newRow);
        $("#tblProductWiseSectionSetupDetials").append(newRow);
   

    }
    function removeProductWiseSectionSetupDetial(id)
    {
        $("#addnewrowbtn").prop("disabled", false);
        var controlToBeRemoved = "#tblProductWiseSectionSetupDetials" + id;
        //alert(controlToBeRemoved);
        $(controlToBeRemoved).remove();
    }
    function SetupCheck()
    {
       
        var index = $("#tblProductWiseSectionSetupDetials").children("tr").length;

        if (index < 1)
        {
            alert("Please Add Detail");
            return false;
        }

        else{
         return true;
        }
   
    }
</script>

LILI_FPMS/Views/ProductWiseSectionSetup/Index.cshtml
@model PaginatedList<LILI_FPMS.Models.TblProductWiseSectionSetup>

<section class="content-header">
    @*<h1>
            Production
        </h1>*@
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Product Wise Section Setup</li>
    </ol>
</section>

@if (TempData["msg"] != null)
{
    <div class="myAlert-top alert alert-success">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success" role="alert">
                    @TempData["msg"]
                </div>
            </div>
        </div>
    </div>
}
@*    <strong>Success!</strong> Indicates a successful or positive action.*@

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="box-body">
            <div class="col-xs-12">
                <div class="col-sm-11">
                    <form asp-action="Index" method="get">
                        <div class="form-actions no-color">
                            <div class="col-sm-12">
                                <div class="col-sm-6">
                                    <input type="text" name="SearchString" value="@ViewData["currentFilter"]" class="form-control" placeholder="Search for...">
                                </div>
                                <div class="col-sm-3">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-search" value="Search"><i class="fa fa-search fa-fw"></i>Search</button>
                                    </span>
                                </div>
                                <div class="col-sm-3">
                                    @*<a asp-action="Index">Back to Full List</a>*@
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
                <div class="col-sm-1">
                    <a class="btn btn-action" href="/ProductWiseSectionSetup/Create">
                        <i class="fa fa-plus fa-fw"></i>Add
                    </a>
                </div>
            </div>

            <div class="grid-table-header">
                <table id="ProductionTable" class="table roundedCorners">
                    <thead>
                        <tr style="background-color:#6c7ae0; color:white; height:50px;">
                            <th style="text-align:center;  width:3%">Id</th>
                            <th style="text-align:center;  width:7%">Plant Id</th>
                            <th style="text-align:center; width:10%">
                                <a style="color:white;" asp-action="Index" asp-route-sortOrder="@ViewData["ProductCodeSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Product Code <i class="fa fa-sort" style="font-size:20px;color:sandybrown;"></i></a>
                            </th>
                            <th style="text-align:center; width:10%">
                                <a style="color:white;" asp-action="Index" asp-route-sortOrder="@ViewData["ProductNameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Product Name <i class="fa fa-sort" style="font-size:20px;color:sandybrown;"></i></a>
                            </th>
                            <th style="text-align:center; width:10%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td style="text-align:center;">@Html.DisplayFor(modelItem => item.Id)</td>
                                    <td style="text-align:center;">@Html.DisplayFor(modelItem => item.PlantId)</td>
                                    <td  style="text-align:center;">@Html.DisplayFor(modelItem => item.ProductCode)</td>
                                    <td  style="text-align:center;">@Html.DisplayFor(modelItem => item.ProductName)</td>

                                    @*<td style="text-align:center;"><a href="/Production/Update/@item.Id"><i class="fa fa-edit" aria-hidden="true" style="font-size:20px;color:#4d4a45"></i></a> | </td>*@
                                    <td style="text-align:center;">
                                    <a href="/ProductWiseSectionSetup/Update/@item.Id"><i class="fa fa-edit" aria-hidden="true" style="font-size:20px;color:#4d4a45"></i></a>|
                                    <a href="#" onclick="Delete('@item.Id')"><i class="fa fa-trash" aria-hidden="true" style="font-size:20px;color:#4d4a45"></i></a>
                                   
                                    </td>
                                </tr>
                            }
                        }
                </table>
            </div>
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }


            <div class="grid-table-footer">
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-default @prevDisabled"
                   style="background-color:#4d4a45; color:white;">
                    <i class="fa fa-angle-left fa-fw"></i>
                    Previous
                </a>
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-default @nextDisabled"
                   style="background-color:#4d4a45; color:white;">
                    <i class="fa fa-angle-right fa-fw"></i>
                    Next
                </a>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.row -->
</section>

<!-- DataTables -->
@*<script src="~/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>*@
@*<script src="~/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>*@



<!-- page script -->
<script>
        //$(function () {
        //    $('#example1').DataTable();
        //});
        function Delete(id){
            var r = confirm("Are you sure you want to Delete?");
            if (r == true) {

                $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("Delete", "ProductWiseSectionSetup")',
                    data: {
                        id: id
                    },
                    error: function (result) {
                        alert("error");
                    },
                    success: function (result) {
                        if (result == true) {
                            var baseUrl = "/Index";
                            alert("Delete Succesful!s");
                            window.location.reload();
                        }
                        else {
                            alert("Can't delete, May have data dependency !");
                        }

                    }
                });
            }
        }
</script>

<style>
    /*table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: left;
        padding: 8px;
    }


    tr:nth-child(even) {
        background-color: #e3d8c3;
    }*/







    table {
        border: 1px solid #e3d8c3;
        border-radius: 13px;
        border-spacing: 0;
    }

    /*table.roundedCorners td,
    table.roundedCorners th {
    border-bottom: 1px solid #e3d8c3;
    padding: 10px;
    }

    table.roundedCorners tr:last-child > td {
        border-bottom: none;
    }*/










    html {
        margin: 40px auto;
    }

    .btn-search {
        background: #286090;
        border-radius: 0;
        color: #fff;
        border-width: 1px;
        border-style: solid;
        border-color: #1c1c1c;
    }

        .btn-search:link, .btn-search:visited {
            color: #fff;
        }

        .btn-search:active, .btn-search:hover {
            background: blue;
            color: #ccc;
        }





    .btn-action {
        background: #286090;
        border-radius: 0;
        color: #fff;
        border-width: 1px;
        border-style: solid;
        border-color: #1c1c1c;
    }

        .btn-action:link, .btn-search:visited {
            color: #fff;
        }

        .btn-action:active, .btn-search:hover {
            background: blue;
            color: #ccc;
        }

    .alert {
        display: none;
    }
</style>